### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by changkun** [changkun/redir#2]
1. [x] Add valid duration: start accessible since
2. [x] Redo stat UI: Add edit table, PV/UV time histograms,
3. [x] GDPR strict: No cookie (stop using google analytics), don’t store a full IP address, transform and hashing it for identification
4. [x] ~~Remove random kind and add tagging: add tags to aliases~~, stat UI should be able to filter it out
5. [x] private and public indexes (admin can specify if a link should be publically listed)
6. [x] ~~group links: random redirect for AB testing~~ not now
7. [x] `redir -dump` to dump all aliases, for crontab backup purpose
